// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "go.opentelemetry.io/collector/config/configopaque"

type Alias struct {
	// MyDateTime corresponds to the JSON schema field "myDateTime".
	MyDateTime *configopaque.String `json:"myDateTime,omitempty" yaml:"myDateTime,omitempty" mapstructure:"myDateTime,omitempty"`
}
